version: "3.4"
services:
  # api-gateway:
  # user:
  #   container_name: users-service
  #   build: backend/services/users/
  #   # volumes:
  #   #   - "backend/services/users:/usr/src/app"
  #   #   - "backend/services/users/package.json:/usr/src/package.json"
  #   ports:
  #     - "3001:3000" # expose ports - HOST:CONTAINER
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@users-db:5431/users_dev
  #     - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5431/users_test
  #     - NODE_ENV=development
  #     - TOKEN_SECRET=changeme
  #   depends_on:
  #     - users-db
  #   links:
  #     - users-db
  # users-db:
  #   container_name: users-db
  #   build: backend/services/users/db
  #   ports:
  #     - "5431:5432" # expose ports - HOST:CONTAINER
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   healthcheck:
  #     test: exit 0

  posts:
    build: backend/services/posts
    ports:
      - "3002:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@posts-db:5432/posts
    depends_on:
      - posts-db
    links:
      - posts-db

  posts-db:
    build: backend/services/posts/db
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=posts
    healthcheck:
      test: exit 0
  # node backend
  node-prod:
    restart: always
    build:
      context: backend
      target: prod
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  # front-end built with react
  react-prod:
    restart: always
    build:
      context: frontend
      target: prod
    ports:
      - "3333:3000"
    depends_on:
      - node-prod

  # nginx is used for ssl termination
  nginx-prod:
    restart: always
    build:
      context: nginx
      target: dev
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - node-prod
      - react-prod

  # postgres is our primary data store
  postgres:
    restart: always
    build: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: docker
